--DB CREATION
CREATE DATABASE "ECOSampleApp_MT";

--USERS AND PERMISSIONS
CREATE USER ecosample WITH PASSWORD 'ecosample';
GRANT ALL PRIVILEGES ON DATABASE "ECOSampleApp_MT" to ecosample;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ecosample;