//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECO.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECO.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The section &quot;eco&quot; was not found in .config file..
        /// </summary>
        internal static string CONFIG_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONFIG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The data context is closed.
        /// </summary>
        internal static string DATA_CONTEXT_CLOSED {
            get {
                return ResourceManager.GetString("DATA_CONTEXT_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The type of the identity attribute is different from the type defined by the entity &apos;{0}&apos;..
        /// </summary>
        internal static string IDENTITY_TYPE_NOT_MATCHED {
            get {
                return ResourceManager.GetString("IDENTITY_TYPE_NOT_MATCHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The persistent context &apos;{0}&apos; is not registered..
        /// </summary>
        internal static string PERSISTENCE_CONTEXT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PERSISTENCE_CONTEXT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The persistent unit &apos;{0}&apos; is not registered..
        /// </summary>
        internal static string PERSISTENCE_UNIT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PERSISTENCE_UNIT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The persistent class &apos;{0}&apos; is not related to any persistence context..
        /// </summary>
        internal static string PERSISTENT_CLASS_NOT_FOUND {
            get {
                return ResourceManager.GetString("PERSISTENT_CLASS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There was an error during the activation of the type &apos;{0}&apos;..
        /// </summary>
        internal static string TYPE_LOAD_EXCEPTION {
            get {
                return ResourceManager.GetString("TYPE_LOAD_EXCEPTION", resourceCulture);
            }
        }
    }
}
